platform :ios, "9.0"

inhibit_all_warnings!
use_frameworks!

target 'XTCAlbum' do

pod 'Masonry'
pod 'AFNetworking', '~> 3.1.0'
pod 'DACircularProgress', '~> 2.3.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDWebImage'
#高德地图
pod 'AMap3DMap', '~> 6.9.0'
pod 'AMapSearch', '~> 6.9.0'
pod 'AMapLocation', '~> 2.6.2'
pod 'INTULocationManager', '~> 4.3.2'
#分享
#精简版微信
#pod 'UMengUShare/Social/ReducedWeChat'
#精简版QQ
#pod 'UMengUShare/Social/ReducedQQ'
#精简版新浪
#pod 'UMengUShare/Social/ReducedSina'
pod 'SAMTextView', '~> 0.2.2'
pod 'IQKeyboardManager', '~> 6.2.0'
pod 'KVNProgress'
pod 'Mantle', '~> 2.0.2'
pod 'EGOCache', '~> 2.1.3'
pod 'VPImageCropper', '~> 0.0.4'
pod 'TPKeyboardAvoiding', '~> 1.3.1'
pod 'TZImagePickerController', '~> 3.2.0'
pod 'FMDB', '~> 2.7.2'
pod 'ZZCircleProgress', '~> 0.0.2'
pod 'TheAmazingAudioEngine', '~> 1.5.8'
pod 'XHLaunchAd', '~> 3.7.2'
pod 'MagicalRecord', '~> 2.3.2'
pod 'ZLCollectionViewFlowLayout'
pod 'GVRSDK'
pod 'HysteriaPlayer', '~> 2.2.2'
#pod 'ICGVideoTrimmer', '~> 1.1'
#pod 'JPVideoPlayer', '= 3.1.1'
pod 'SMCalloutView', '= 2.1.5'
pod 'CocoaLumberjack', '~> 3.5.2'
pod 'MZTimerLabel', '~> 0.5.4'
pod 'SCSiriWaveformView', '~> 1.1.1'
pod 'RegexKitLite'
pod 'SnapKit'
pod 'GPUImage', '~> 0.1.7'
pod 'JPImageresizerView', '= 0.5.3'
pod 'YYImage', '~> 1.0.4'
pod 'UINavigation-SXFixSpace', '~> 1.2.1'


end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
