# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkDemo
  pod 'Apollo'
  
  #存储model数据
  pod 'AutoSQLiteSwift', '~> 0.0.9'

  target 'NetworkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkDemoUITests' do
    # Pods for testing
  end

end
